### ISSUE TITLE
Information leakage

### ISSUE THREAD

**Issue by LMissher** [Kqingzheng/ModWaveMLP#1]
Hello, I think the [code using wavelet decomposition](https://github.com/Kqingzheng/ModWaveMLP/blob/06166fed2685a15995685380bfd8e5fdfb61f53d/Datasets/generate_training_data_wt.py#L16-L29) involved information leakage. For details, please refer to this [blog](https://zhuanlan.zhihu.com/p/676126252).

**Comment by Kqingzheng** [comment]
Thank you for your suggestion, we have considered this issue before because if we consider the information leakage compared to the ablation model with the removal of the wavelet noise reduction module, then the model should achieve good results on most of the traffic prediction datasets (e.g., pems04,pems07), but this is not the case in our experimental results. [The article](https://arxiv.org/abs/2310.06119) pointed out the difference between metr-la, pems-bay and other traffic prediction datasets, and we were thinking whether the good results of our method are related to the datasets.

Based on your suggestions, we are optimizing the code.

To avoid any misunderstanding, we remove the paperwithcode link for now.

**Comment by LMissher** [comment]
I think future information should not be used regardless of whether it is useful or not. Looking forward to the new code and results based on the input $x$.

Best regards.

**Comment by Kqingzheng** [comment]
Ok, we'll update the code and results based on your suggestions, and if you're interested in changing the code, you're also welcome to provide a PR and we'll merge it in the master branch
